require("setup.plugins-setup")
require("setup.core.options")
require("setup.core.keymaps")
require("setup.core.colorscheme")
require("setup.plugins.nvim-tree")
require("setup.plugins.lualine")
require("setup.plugins.telescope")
require("setup.plugins.nvim-cmp")
